<?php
/********************************************************
	lang/nn_NO/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

$composeHStrings[0] = "Emne";
$composeHStrings[1] = "Fr&aring;";
$composeHStrings[2] = "&Aring;t";
$composeHStrings[3] = "Avrit &aring;t";
$composeHStrings[4] = "L&oslash;yndeavrit &aring;t";
$composeHStrings[5] = "Dato";


$composeStrings[0] = "Brevark";
$composeStrings[1] = "Send brevet";
$composeStrings[2] = "Last upp";
$composeStrings[3] = "Signer";
$composeStrings[4] = "Vedlegg";
$composeStrings[5] = "Syn kjenningane";
$composeStrings[6] = "L&oslash;yn kjenningane";
$composeStrings[7] = "Br&oslash;dtekst:";
$composeStrings[8] = "F&oslash;r p&aring;";
$composeStrings[9] = "%d orda %s:\n";
$composeStrings[10] = "--- Upphavlegt brev ---\n";
$composeStrings[11] = "Lat att vindauga";

$composeStrings[12] = "Gjer stavekontroll";
$composeStrings[13] = "Retta stavingi";
$composeStrings[14] = "Ingen endringar";
$composeStrings[15] = "Mogelege stavefeil";
$composeStrings[16] = "Rettingar";
$composeStrings[17] = "yversj&aring;";
$composeStrings[18] = "slett";

$composeStrings["title"] = "Brevark";

$composeErrors[0] = "Emnelina er tom. F&oslash;r helst inn eit emne elder klikk \"".$composeStrings[1]."\" att for &aring; senda.";
$composeErrors[1] = "\"Fr&aring;\"-feltet er tomt.  F&oslash;r inn e-posttilskrifta di.";
$composeErrors[2] = "\"&Aring;t\"-feltet er tomt.  Set inn den tilskrifta som vantar.";
$composeErrors[3] = "Upplastingi var mislukka";
$composeErrors[4] = "Ingen filer mottekne.";
$composeErrors[5] = "Som eit tiltak imot uynskt reklame hev du einast h&oslash;ve til &aring; senda &aring;t %1 menneske (%2 ialt for kvar &oslash;kti) kvart %3 sekund.";

$composeErrors[6] = "Ingen stavefeil funne.";
$composeErrors[7] = "Stavekontroll ikkje tilgjengeleg for det avmerkte m&aring;let.";
$composeErrors[8] = "(%s ordbok nytta)";
?>