<?php
/********************************************************
	lang/nn_NO/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

$cStrings[0] = "Kjenningar";
$cStrings[1] = "F&oslash;r ny kjenning";
$cStrings[2] = " kjenning";
$cStrings[3] = "Namn";
$cStrings[4] = "E-tilskrift";
$cStrings[5] = "URL";
$cStrings[6] = "Gruppa";
$cStrings[7] = "Merknader";
$cStrings[8] = "F&oslash;r upp/brigda kjenningen";
$cStrings[9] = "E-tilskrift";
$cStrings[10] = "Brevark";


$cErrors[0] = "Du hev ikkje skrive upp nokon av kjenningane dine her enno.";


?>