<?php
/********************************************************
	lang/nn_NO/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

$efStrings[0] = "Handtering av brevpermar";
$efStrings[1] = "Laga ny perm";
$efStrings[2] = "Lag permen: ";
$efStrings[3] = "Lag";
$efStrings[4] = "Slett permen";
$efStrings[5] = "Slett";
$efStrings[6] = "Umd&oslash;yp permen";
$efStrings[7] = "Umd&oslash;yp";
$efStrings[8] = "Permar i bruk";
$efStrings[9] = "Tak i bruk";
$efStrings[10] = "Ubrukte permar";
$efStrings[11] = "Tak ut av bruk";


$errors[0] = "Lag perm: ";
$errors[1] = "Fekk ikkje laga permen: ";
$errors[2] = "&Oslash;ydelegg permen: ";
$errors[3] = "Fekk ikkje &oslash;ydelagd permen: ";
$errors[4] = "Umd&oslash;ypt permen: ";
$errors[5] = "Fekk ikkje umd&oslash;ypt permen: ";
$errors[6] = "Permstudnad einast tilgjengeleg for IMAP-kontoar.";

?>