<?php 
/********************************************************
	lang/nn_NO/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//translators: leave following include
include("./modules/wmail/lang/eng/login.inc");

$loginStrings[0]="Brukarnamn";
$loginStrings[1]="Lausnord";
$loginStrings[2]="Serverar";
$loginStrings[3]="Slag";
$loginStrings[4]="Hovud-/rotperm";
$loginStrings[5]="M&aring;lvald";
$loginStrings[6]="Logg inn";

$loginErrors[0]="Ein us&aelig;tande vert";
$loginErrors[1]="Feil: katalogen til \"uploads\" ikkje funnen";
$loginErrors[2]="Feil: perm for \"users\" ikkje funnen";
$loginErrors[3]="Feil: perm for \"sessions\" ikkje funnen";

?>