<?php
/********************************************************
	lang/nn_NO/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

$mainMessages["delete"] = "Sletta %n brev";
$mainMessages["move"] = "Flytte %n brev &aring;t %f";

$mainStrings[0] = "Syner %p av %n";
$mainStrings[1] = " funn.";
$mainStrings[2] = "F&oslash;rre";
$mainStrings[3] = "";
$mainStrings[4] = "Neste";
$mainStrings[5] = "";
$mainStrings[6] = "Emne";
$mainStrings[7] = "&Aring;t";
$mainStrings[8] = "Fr&aring;";
$mainStrings[9] = "Dato";
$mainStrings[10] = "Slett";
$mainStrings[11] = "T&oslash;m skrotpostpermen";
$mainStrings[12] = "Flytt";
$mainStrings[13] = "S&oslash;k";
$mainStrings[14] = "Storleik";
$mainStrings[15] = "unamna";
$mainStrings[16] = "Syn fram";
$mainStrings[17] = "Sj&aring; etter post";
$mainStrings[18] = "Slett alle";
$mainStrings[19] = "Avbrjot";
$mainStrings[20] = "Avmerkt(e) brev skal visast i  %b stand.";
$mainStrings[21] = "opna";
$mainStrings[22] = "uopna";


$mainErrors[0] = "Ingen brev funne i denne permen";
$mainErrors[1] = "Ingen brev i denne permen";
$mainErrors[2] = "Fekk ikkje flytt brevet &aring;t skrotpermen.";
$mainErrors[3] = "Fekk ikkje merkt av at brevet er sletta.";
$mainErrors[4] = "Fekk ikkje flytt brevi.";
$mainErrors[5] = "Perm for skrotpost ikkje vald.";
$mainErrors[6] = "Fekk ikkje t&oslash;mt permen for skrotpost.";
$mainErrors[7] = "Er du viss p&aring; at du vil sletta KVART EINASTE brev i %f?";
$mainErrors[8] = "For f&aring; f&aring; flytt deim trykkjer du p&aring; pila nedanum kolonneyveskriftene.<br>N&aring;r du er ferdug let du berre att vindauga.";



?>