<?php
/********************************************************
	lang/nn_NO/prefs.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

$prefHeaderStrings[0] = "Val";
$prefHeaderStrings[1] = "&Aring;lment";
$prefHeaderStrings[3] = "Tilnamn";
$prefHeaderStrings[2] = "Utsj&aring;nad";

											
$prefsStrings["0.0"] = "Tilnamn";
$prefsStrings["0.1"] = "Namn: ";
$prefsStrings["0.2"] = "E-posttilskrift: ";
$prefsStrings["1.0"] = "Millomfolkelegt";
$prefsStrings["1.1"] = "Stadsetning: ";
$prefsStrings["1.2"] = "Teiknkoding: ";
$prefsStrings["1.3"] = "Tidssona: ";
$prefsStrings["1.4"] = "Klokkeval: ";
$prefsStrings["1.5"] = array(12=>"12-timarsklokka", 24=>"24-timarsklokka");
$prefsStrings["2.0"] = "Brevyversyn";
$prefsStrings["2.1"] = "Tak med upp mot ";
$prefsStrings["2.2"] = " brev um gongen";
$prefsStrings["2.3"] = "Tak med storleiken";
$prefsStrings["2.4"] = "Rada brevi etter ";
$prefsStrings["2.5"] = "";
$prefsStrings["2.6"] = "Rekkjefylgd: ";
$prefsStrings["2.7"] = "";
$prefsStrings["2.8"] = "Vis permyversynet";
$prefsStrings["2.9"] = "Permyversyn";
$prefsStrings["2.10"] = "Sj&aring; etter post kvart %n sekund";
$prefsStrings["2.11"] = "Syn verktylina p&aring; %m";
$prefsStrings["2.12"] = array("b"=>"botnen", "t"=>"toppen", "bt"=>"botn og topp");
$prefsStrings["2.13"] = "For &aring; byta um p&aring; kolonnor: ";
$prefsStrings["2.14"] = "gjer kolonneumbyte her";
$prefsStrings["3.0"] = "Brevhandsaming";
$prefsStrings["3.1"] = "Lagra all utg&aring;ande post.";
$prefsStrings["3.2"] = "Lagra utposten i: ";
$prefsStrings["3.3"] = "";
$prefsStrings["3.4"] = "Lat skrotposten verta sletta av seg sj&oslash;lv.";
$prefsStrings["3.5"] = "Set skrotposten inn i permen: ";
$prefsStrings["3.6"] = "";
$prefsStrings["3.7"] = "Hovud-/rotperm: ";
$prefsStrings["3.8"] = "Annan";
$prefsStrings["3.9"] = "L&oslash;yn permar ute av bruk";
$prefsStrings["3.10"] = "Syn tilgjengleg lagerplass %m";
$prefsStrings["3.11"] = array(""=>"ikkje syn", "m"=>"i brevyversynet", "f"=>"i permyversynet");
$prefsStrings["4.0"] = "Brevopning";
$prefsStrings["4.1"] = "Brev vert opna i same vindauga";
$prefsStrings["4.2"] = "Hermingar vert fargelagde";
$prefsStrings["4.3"] = "(N&aring;r valet er p&aring;slege, kan det gjera systemet treigt.)";
$prefsStrings["4.4"] = "URLar vert gjorde um til lenker";
$prefsStrings["4.5"] = "HTML-brev vert opna i html-l&aelig;gje";
$prefsStrings["4.6"] = "Bil&aelig;te vert synte inne i teksti";
$prefsStrings["4.7"] = "Syn lenker til &aring; bledja med.";
$prefsStrings["4.8"] = "Gjenombledjing av posten utan at det synst at brevi hev vore opna.";
$prefsStrings["5.0"] = "Namnetrekk";
$prefsStrings["5.1"] = "Namnetrekket skal som utgangspunkt takast med ";
$prefsStrings["5.2"] = "";
$prefsStrings["6.0"] = "Brevark";
$prefsStrings["6.1"] = "Syn kjenningane";
$prefsStrings["6.2"] = "Syn felta &laquo;Avrit &aring;t&raquo;/&laquo;L&oslash;yndeavrit &aring;t&raquo;";
$prefsStrings["6.3"] = "Lat att etter sending";
$prefsStrings["6.4"] = "Brevarket i same rama";
$prefsStrings["7.0.0"] = "Disk- &amp; permval";
$prefsStrings["7.0.1"] = "Hermingsval";
$prefsStrings["7.1"] = "Syn talet p&aring; uopna brev";
$prefsStrings["7.2"] = "Friska upp permyversynet kvart %n sekund";


$sort_fields=array("DATE"=>"Datoen", "SUBJECT"=>"Emnet", "SIZE"=>"Storleiken");
$sort_orders=array("ASC"=>"Aukande", "DESC"=>"Minkande");

$prefsButtonStrings = array( 0=> "Uppdater", 1=>"Set i verk", 2=> "Avbrjot", 3=> "Set i utgongsl&aelig;gje");

$prefs_new_user = "Det verkar som du er logga inn for fyrste gong... vel komen!<br>";
$prefs_new_user .= "Ver greid og g&aring; gjenom fylgjande innstillingar f&oslash;re du trykkjer p&aring; \"Set i verk\"-knappen.";
?>