<?php
/********************************************************
	lang/nn_NO/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

$rmStrings[0] = "Index";
$rmStrings[1] = "Svara";
$rmStrings[2] = "Vidaresend";
$rmStrings[3] = "Slett ikkje";
$rmStrings[4] = "Slett";
$rmStrings[5] = "Flytt";
$rmStrings[6] = "Deler";
$rmStrings[7] = "Merk: dette er eit HTML-brev. ";
$rmStrings[8] = "Trykk her for &aring; opna brevet.";
$rmStrings[9] = "Kjelda";
$rmStrings[10] = "Storleik";
$rmStrings[11] = "Lat att uopna";
$rmStrings[12] = "Syn brevhovud";
$rmStrings[13] = "Seg fr&aring; um reklamebrev";
$rmStrings[14] = "Svara &aring;t alle";
$rmStrings[15] = "Du hev svara p&aring; brevet tidlegare";
$rmStrings[16] = "Prenta";

?>