<?php
/********************************************************
	lang/nn_NO/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

$searchErrors["field"] = "Umogelegt s&oslash;kjeverde:  Ugildt felt";
$searchErrors["empty"] = "Umogelegt s&oslash;kjeverde:  Tom s&oslash;kjestreng";
$searchErrors["date"] = "Umogelegt s&oslash;kjeverde:  Utferdingsdato vantar";

?>