<?php
$mapeo = array(
	"contact_first_name" => "Nombre",
	"contact_middle_name" => "Inicial",
	"contact_last_name" => "Apellidos",
	"contact_title" => "Title",
	"contact_birthday" => "Birthday",
	"contact_company" => "Organización",
	"contact_company_phone" => "Número de centralita de la organización",
	"contact_email" => "E-mail Address",
	"contact_email2" => "Dirección de correo electrónico 2",
	"contact_phone" => "Particular",
	"contact_phone2" => "Home Phone 2",
	"contact_mobile" => "Mobile Phone",
	"contact_address1" => "Calle del trabajo",
	"contact_address2" => "Home Street",
	"contact_city" => "Ciudad de trabajo",
	"contact_state" => "Provincia o estado de trabajo",
	"contact_zip" => "Código postal del trabajo",
	"contact_country" => "País de trabajo",
	"contact_notes" => "Notes",
	"contact_business_phone" => "Teléfono del trabajo",
	"contact_business_phone2" => "Business Phone 2",
	"contact_fax" => "Business Fax",
	"contact_website" => "Página Web",
	"contact_department" => "Department",
	"contact_manager" => "Nombre del director",
	"contact_assistant" => "Assistant's Name",
	);
$mapeoAlt = array(
	"contact_city" => "Home City,",
	"contact_state" => "Home State,",
	"contact_zip" => "Home Postal Code,",
	"contact_country" => "Home Country,",
	"contact_fax" => "Home Fax,",
    );
?>